baseURL = "https://drupaldoesnotexists.github.io/notes/"
languageCode = "ru-ru"
title = "Публичный блог @dne"
theme = "nostyleplease"

[params]
tgSite = "kbE3j1NL"

[taxonomies]
category = 'categories'
tag = 'tags'
