# Telegram channel notification
name: Telegram notify

# Run on push
on: [push]
jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'post:')"
    steps:
      - name: Split commit name
        env:
          COMMIT_NAME: ${{ github.event.head_commit.message }}
        id: split
        run: echo "::set-output name=fragment::${COMMIT_NAME##*post:}"
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            Новый пост!

            [${{ steps.split.outputs.fragment }}](https://${{ github.repository_owner }}.github.io/${{ github.repository_name }}/posts/${{ steps.split.outputs.fragment }})
            Автор: **${{ github.event.head_commit.author.name }}**


